# -*- coding: utf-8 -*-
"""MLModel_PSO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SrluZlaLu-cvgNRAbbKeod9Wvjj9rzjy
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# !pip install -U -q PyDrive
# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
# from google.colab import auth
# from oauth2client.client import GoogleCredentials

# auth.authenticate_user()
# gauth = GoogleAuth()
# gauth.credentials = GoogleCredentials.get_application_default()
# drive = GoogleDrive(gauth)

# link = 'https://drive.google.com/file/d/1SUY_yuEPHfNciNcTV5BQUf4_NGNzcj5N/view?usp=sharing'

# id = link.split('d/')[1].split('/view?')[0]
# print (id)

# downloaded = drive.CreateFile({'id':id})
# downloaded.GetContentFile('dataset.csv')

data = pd.read_csv('diabetes.csv')
data.head()

data.isnull().sum()

data.duplicated().sum()

data.corr()

#Drop the column that have low correlation with the independent(diabetes) variable

data = data.drop(['BloodPressure', 'SkinThickness'], axis=1)

data

#Train test split
X = data.drop('Outcome', axis=1)
Y = data['Outcome']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
Y_test

model = LogisticRegression()
model.fit(X_train, Y_train)

model.predict(X_test)

accuracy_score(Y_test, model.predict(X_test))

import pickle

filename = "model.pickle"

# save model
pickle.dump(model, open(filename, "wb"))
